base_model: /workspace/home/vinhnq29/zac2023-main/models_hub/vinallama-7b-chat
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizerFast

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /workspace/home/vinhnq29/zac2023-main/data_hub/ViMathQA/train_v1/input_output_vinallama-00000-of-00001.parquet
    type: input_output
dataset_prepared_path:
val_set_size: 0.05
eval_sample_packing: false
output_dir: /workspace/home/vinhnq29/zac2023-main/checkpoints/vinallama-7b-chat-qlora-2024-04-07-05-53-35

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: false

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 4
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-4

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention: 
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 1
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 2
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
